# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerdns', '0034_auto_20161115_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainmetadata',
            name='kind',
            field=models.CharField(max_length=31, verbose_name='kind'),
        ),
    ]
