FROM zefciu/python-base
MAINTAINER Pylabs <pylabs@allegro.pl>
RUN pip install django==1.8 mysqlclient pyyaml django-extensions factory_boy djangorestframework django-rest-swagger django-filter
RUN rm -rf /tmp/pip*
